# Generated by Django 4.2 on 2023-04-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discography', models.CharField(max_length=200)),
                ('debut_date', models.DateField()),
                ('agency', models.CharField(max_length=50)),
                ('genre', models.CharField(blank=True, choices=[('pop', 'Pop'), ('rock', 'Rock'), ('metal', 'Metal'), ('hard rock', 'Hard Rock'), ('progressive', 'Progressive')], max_length=50, null=True)),
            ],
        ),
    ]
